export const blogs = [
  {
    id: 6,
    title: "SOLO UNA IMAGEN Y POCO TEXTO 6",
    subtitle: "This blog only has a main image and some text.",
    imageUrl: "/new-gen-patio-react/assets/images/Products/Patios&Pergolas/Attached/01.webp",
    content: ["Texto descriptivo del blog que armen."],
    date: "2024-02-01",
  },
  {
    id: 5,
    title: "BLABLABLA 5",
    subtitle: "Keep your pergolas and patios in top condition",
    imageUrl: "/new-gen-patio-react/assets/images/Products/Patios&Pergolas/Attached/01.webp",
    content: ["Regular maintenance prevents wear and extends lifespan..."],
    secondaryImage: "/new-gen-patio-react/assets/images/Products/Patios&Pergolas/Attached/02.webp",
    moreContent: ["Here is another paragraph after the secondary image."],
    finalImage: "/new-gen-patio-react/assets/images/Products/Patios&Pergolas/Attached/01.webp",
    lastContent: ["This is the final paragraph wrapping up the blog post."],
    date: "2023-12-20",
  },
  {
    id: 4,
    title: "SOLO UNA IMAGEN Y POCO TEXTO 4",
    subtitle: "This blog only has a main image and some text.",
    imageUrl: "/new-gen-patio-react/assets/images/Products/Patios&Pergolas/Attached/01.webp",
    content: ["Texto descriptivo del blog que armen."],
    date: "2024-02-01",
  },
  {
    id: 3,
    title: "SOLO UNA IMAGEN Y POCO TEXTO 3",
    subtitle: "This blog only has a main image and some text.",
    imageUrl: "/new-gen-patio-react/assets/images/Products/Patios&Pergolas/Attached/01.webp",
    content: ["Texto descriptivo del blog que armen."],
    date: "2024-02-01",
  },
  {
    id: 2,
    title: "SOLO UNA IMAGEN Y POCO TEXTO 2",
    subtitle: "This blog only has a main image and some text.",
    imageUrl: "/new-gen-patio-react/assets/images/Products/Patios&Pergolas/Attached/01.webp",
    content: ["Texto descriptivo del blog que armen."],
    date: "2024-02-01",
  },
  {
    id: 1,
    title: "SOLO UNA IMAGEN Y POCO TEXTO 1",
    subtitle: "This blog only has a main image and some text.",
    imageUrl: "/new-gen-patio-react/assets/images/Products/Patios&Pergolas/Attached/01.webp",
    content: ["Texto descriptivo del blog que armen."],
    date: "2024-02-01",
  },
];